# ZigDNS Configuration File
# Place this file at /etc/zdns/config.toml

[server]
# Address to bind DNS server (default: 0.0.0.0:53)
listen_addr = "0.0.0.0:53"

# Address to bind QUIC server (default: 0.0.0.0:853)
listen_quic_addr = "0.0.0.0:853"

# Protocol to use: udp, dot, doh, doq (default: udp)
protocol = "udp"

# Run as daemon (default: false)
daemon = false

# Enable verbose logging (default: false)
verbose = false

[upstream]
# Primary upstream DNS server (default: 1.1.1.1:53)
primary = "1.1.1.1:53"

# Secondary upstream DNS server (default: 8.8.8.8:53)
secondary = "8.8.8.8:53"

# Upstream QUIC server for DoQ (default: 1.1.1.1:853)
quic = "1.1.1.1:853"

[web3]
# Enable Web3 domain resolution (default: true)
enabled = true

# ENS endpoint (Ethereum Name Service)
ens_endpoint = "https://mainnet.infura.io/v3/YOUR_INFURA_KEY"

# Unstoppable Domains endpoint
unstoppable_endpoint = "https://polygon-mainnet.g.alchemy.com/v2/YOUR_ALCHEMY_KEY"

# GhostChain ZNS endpoint
zns_endpoint = "https://rpc.ghostchain.io"

# CNS QUIC endpoint
cns_endpoint = "https://cns.quic.network"

[security]
# Enable post-quantum cryptography (default: false)
enable_post_quantum = false

# Auto-generate certificates for TLS/QUIC (default: true)
auto_generate_certs = true

# Path to custom certificate file
cert_path = "/etc/zdns/certs/server.crt"

# Path to custom private key file
key_path = "/etc/zdns/certs/server.key"

[cache]
# Cache size in number of entries (default: 4096)
size = 4096

# Minimum TTL in seconds (default: 60)
ttl_min = 60

# Maximum TTL in seconds (default: 3600)
ttl_max = 3600

# Enable zero-copy operations (default: true)
zero_copy = true

[performance]
# Maximum concurrent queries (default: 10000)
max_concurrent_queries = 10000

# Enable performance optimizations (default: true)
optimizations = true

[blocklist]
# Enable ad/malware blocking (default: true)
enabled = true

# Update interval for blocklists (default: 86400 seconds = 24 hours)
update_interval = 86400

# Blocklist sources (URLs to download)
sources = [
    "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts",
    "https://adguardteam.github.io/HostlistsRegistry/assets/filter_9.txt",
    "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/multi.txt",
    "https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/DNSFilter/sections/adservers.txt",
    "https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt"
]

[logging]
# Log level: debug, info, warn, error (default: info)
level = "info"

# Log file path (default: stdout)
file = "/var/log/zdns.log"

# Enable log rotation (default: true)
rotate = true

# Maximum log file size in MB (default: 10)
max_size = 10

# Number of log files to keep (default: 5)
max_files = 5